defaults: &defaults
  url: redis://localhost:6379
  db: 1

development:
  <<: *defaults
qa:
  url: "redis://<%= ENV['REDIS_HOSTNAME'] %>:<%= ENV['REDIS_PORT'] %>"
  db: "<%= ENV['REDIS_RDS_NAME'] %>"
  password: "<%= ENV['REDIS_PASSWORD'] %>"

test:
  url: "redis://<%= ENV['REDIS_HOSTNAME'] %>:<%= ENV['REDIS_PORT'] %>"
  db: "<%= ENV['REDIS_RDS_NAME'] %>"

staging:
  url: "redis://<%= ENV['REDIS_HOSTNAME'] %>:<%= ENV['REDIS_PORT'] %>"
  db: "<%= ENV['REDIS_RDS_NAME'] %>"
  password: "<%= ENV['REDIS_PASSWORD'] %>"

production:
  url: "redis://<%= ENV['REDIS_HOSTNAME'] %>:<%= ENV['REDIS_PORT'] %>"
  db: "<%= ENV['REDIS_RDS_NAME'] %>"
  password: "<%= ENV['REDIS_PASSWORD'] %>"
